name: Pre-release

on:
  push:
    branches:
      - develop
      - 'feature/**'
      - 'release/**'

permissions:
  contents: read
  packages: write

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Generate pre-release version
        id: version
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          BRANCH_SAFE=$(echo $BRANCH | sed 's/[^a-zA-Z0-9]/-/g')
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          VERSION=$(node -p "require('./package.json').version")
          PRERELEASE_VERSION="${VERSION}-${BRANCH_SAFE}.${TIMESTAMP}"
          npm version $PRERELEASE_VERSION --no-git-tag-version
          echo "version=$PRERELEASE_VERSION" >> $GITHUB_OUTPUT
      
      - name: Publish pre-release to npm
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
      
      - name: Build and push Docker pre-release
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:${{ steps.version.outputs.version }}
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}:next
        env:
          DOCKER_REGISTRY: ghcr.io